In [14]:
#Def 1

import numpy as np
def resolution (a,b):
    n = len(a)
    x = n*[0]
    x[n-1] = b[n-1]/a[n-1][n-1]
    for i in range(n-2,-1,-1):
      s=0
      for j in range(i+1,n):
        s = s + (a[i][j]*x[j])
      x[i] = (b[i] - s) /a[i][i]
    return x


a = np.array([[1,2,3,4],[0,5,6,7],[0,0,8,9],[0,0,0,10]])
b = np.array([5,4,4,2])

print("Resoluçaõ a partir do def:")
print(resolution(a,b))
print("")
print("Resoluçaõ pelo linalg.solver:")
resp = np.linalg.solve(a,b)
print(resp)


Resoluçaõ a partir do def:
[2.995, 0.18999999999999995, 0.275, 0.2]

Resoluçaõ pelo linalg.solver:
[2.995 0.19  0.275 0.2  ]


In [16]:

#Def 2

import numpy as np
def resolution (a,b):
    n = len(a)
    m = n*[0]
    
    for k in range(0,n-1):
      for i in range(k+1,n):
        m = a[i][k]/a[k][k]
        a[i][k]=0
        for j in range(k+1,n):
          a[i][j] = a[i][j] - (m*a[k][j])
          b[i] = b[i] - (m*b[k])
          
  
    return a

a = np.array([[2,(1),(-3)], [-1,3,(2)], [(3),(1),(-3)]])
b = np.array([-1,12,0])

print("Matriz inicial")
print(a)
print("")
print("Matriz final / P.S: Está arredondando os valores")

print(resolution(a,b))

#Matriz final,se não estivesse arredondando para baixo, seria:
#[[ 2,  1,   -3],
#[ 0,  7/2, 1/2], -----> 7/2 => 3,5 => 3
#[ 0,  0,  11/7]])

Matriz inicial
[[ 2  1 -3]
 [-1  3  2]
 [ 3  1 -3]]

Matriz final / P.S: Está arredondando os valores
[[ 2  1 -3]
 [ 0  3  0]
 [ 0  0  1]]
